#%RAML 1.0 DataType
type: array
items:
  type: object
  properties:
    companyName:
      type: string
      required: true
      example: "TravelOnTip"   
    availableSeats:
      type: integer
      required: true
      example: 20
    departureDateTime:
      type: string
      example: "2019-04-30T16:41:41"
    travelRoute:
      type: object
      properties:
        destinationLocation:
          type: object
          required: true
          properties:  
            locationDesc:
              type: string
              required: true
              example: "Klang Malaysia"
        originLocation:
          type: object
          properties: 
            locationDesc:
              type: string
              required: true
              example: "Beauna Vista Singapore"