 #%RAML 1.0 Library
usage:
traits:
  transactionId: !include /libraries/common/traits/headers-transactionId-trait.raml  
  companyName: !include /libraries/common/traits/queryParams-copmanyName-trait.raml
  departureLocation: !include /libraries/common/traits/queryParams-departureLocation-trait.raml
  destinationLocation: !include /libraries/common/traits/queryParams-destinationLocation-trait.raml
  requestTimeZone: !include /libraries/common/traits/queryParams-requestTimeZone-trait.raml